#!/usr/bin/env python3
"""The 100 short subtasks the multi-task benchmark is built from.

Written exactly the way `tasks.py` writes the single-task benchmark: one literal entry per
subtask, naming the objects and rooms, with `spawn`, `goal` and `plan` supplied by a shape
in `task_shapes.py`. `build_tasks` verifies these with the same code that verifies the
single-task set - it replays every reference plan, checks the furniture is really in the
room the sentence claims, checks the movable is a category the dataset can build, and
applies the same in-versus-on rule. Nothing here re-checks any of that.

Four primitives each, so three or four fit in one instruction a person would say. The
combinations are built in `build_multitask.py`; the only property it must enforce that
the builder cannot is that the subtasks in one instruction use **distinct movables** -
that is what makes them independent, and what lets the expected-cost objective decompose
into a pairwise matrix.

`data/tasks.json` is untouched by any of this.
"""

from task_shapes import (carry_one, confer_in_place, fetch_heat_serve, heat_and_serve,
                         retrieve_one, stow_closed, stow_one, switch_one)


def sub(text, shape, rooms=None, dependent=()):
    """One subtask, in the same shape as a `tasks.py` entry.

    **No `extraction` here.** `tasks.py` does not carry one either - `build_tasks` attaches
    stage-1 ground truth from `data/extraction_truth.json`, authored by reading each
    sentence, and `build_multitask` does the identical thing from
    `data/subtask_extraction.json`. Computing it here is what went wrong before: this put
    every name into `uncertain` and left `stated` and `dependent` empty, so a task that says
    "the wineglass from the kitchen countertop" was recorded as saying nothing about where
    the wineglass or the countertop is. The extractor, which reads the sentence correctly and
    answers in the three classes the single-task set uses, was then marked wrong on all 500
    instructions - and, worse, `populate` was handed the wrong classes, so the RSN guessed
    rooms for objects whose room the instruction had stated outright.

    `dependent` is still accepted and ignored, so the literal entries below need no edit.
    """
    return {"task": text, "rooms": rooms or {}, **shape}


def inside(obj, target):
    return {"object": obj, "relation": "INSIDE", "target": target}


SUBTASKS = {
    "Beechwood_0_int": [
        sub("put the wineglass from the kitchen countertop on the kitchen breakfast table",
            carry_one("wineglass", "countertop", "breakfast_table"),
            {"countertop": "kitchen_0", "breakfast_table": "kitchen_0"}),
        sub("put the newspaper from the armchair on the sofa",
            carry_one("newspaper", "armchair", "sofa"),
            {"armchair": "living_room_0", "sofa": "living_room_1"}),
        sub("put the magazine from the desk in the office bookcase",
            stow_one("magazine", "desk", "bookcase"),
            {"desk": "private_office_0", "bookcase": "private_office_0"}),
        sub("put the rag from the kitchen countertop in the bathroom furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "kitchen_0", "furniture_sink": "bathroom_0"}),
        sub("take the textbook out of the kitchen bookcase and put it on the desk",
            retrieve_one("textbook", "bookcase", "desk"),
            {"bookcase": "kitchen_0", "desk": "private_office_0"},
            [inside("textbook", "bookcase")]),
        sub("put the plate from the dining room coffee table on the kitchen breakfast table",
            carry_one("plate", "coffee_table", "breakfast_table"),
            {"coffee_table": "dining_room_0", "breakfast_table": "kitchen_0"}),
        sub("put the notebook from the sofa in the office bookcase",
            stow_one("notebook", "sofa", "bookcase"),
            {"sofa": "living_room_1", "bookcase": "private_office_0"}),
        sub("take the hand towel out of the bathroom furniture sink and put it on the armchair",
            retrieve_one("hand_towel", "furniture_sink", "armchair"),
            {"furniture_sink": "bathroom_0", "armchair": "living_room_0"},
            [inside("hand_towel", "furniture_sink")]),
        sub("put the bowl from the kitchen breakfast table on the dining room coffee table",
            carry_one("bowl", "breakfast_table", "coffee_table"),
            {"breakfast_table": "kitchen_0", "coffee_table": "dining_room_0"}),
        sub("put the mail from the desk on the armchair",
            carry_one("mail", "desk", "armchair"),
            {"desk": "private_office_0", "armchair": "living_room_0"}),
        sub("switch on the living room floor lamp", switch_one("floor_lamp"),
            {"floor_lamp": "living_room_0"}),
        sub("put the tablespoon from the kitchen countertop away in the kitchen bottom cabinet",
            stow_closed("tablespoon", "countertop", "bottom_cabinet"),
            {"countertop": "kitchen_0", "bottom_cabinet": "kitchen_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("take the apple pie from the kitchen countertop, heat it in the oven, and put it on the living room breakfast table",
            heat_and_serve("apple_pie", "countertop", "oven", "breakfast_table"),
            {"countertop": "kitchen_0", "oven": "kitchen_0", "breakfast_table": "living_room_0"}),
        sub("take the bottle of soup out of the fridge, warm it in the microwave, and leave it on the living room breakfast table",
            fetch_heat_serve("bottle_of_soup", "fridge", "microwave", "breakfast_table"),
            {"fridge": "kitchen_0", "microwave": "kitchen_0", "breakfast_table": "living_room_0"}),
        sub("put the plate from the kitchen countertop in the dishwasher and run it",
            confer_in_place("plate", "countertop", "dishwasher"),
            {"countertop": "kitchen_0", "dishwasher": "kitchen_0"}),
    ],
    "Benevolence_1_int": [
        sub("put the wineglass from the dining room countertop on the breakfast table",
            carry_one("wineglass", "countertop", "breakfast_table"),
            {"countertop": "dining_room_0", "breakfast_table": "dining_room_0"}),
        sub("put the newspaper from the sofa in the corridor bookcase",
            stow_one("newspaper", "sofa", "bookcase"),
            {"sofa": "living_room_0", "bookcase": "corridor_0"}),
        sub("put the rag from the kitchen countertop in the furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "kitchen_0", "furniture_sink": "kitchen_0"}),
        sub("take the sponge out of the furniture sink and put it on the console table",
            retrieve_one("sponge", "furniture_sink", "console_table"),
            {"furniture_sink": "kitchen_0", "console_table": "corridor_0"},
            [inside("sponge", "furniture_sink")]),
        sub("put the plate from the dining room countertop on the sofa",
            carry_one("plate", "countertop", "sofa"),
            {"countertop": "dining_room_0", "sofa": "living_room_0"}),
        sub("put the notebook from the console table in the living room bookcase",
            stow_one("notebook", "console_table", "bookcase"),
            {"console_table": "corridor_0", "bookcase": "living_room_0"}),
        sub("put the bowl from the breakfast table on the kitchen countertop",
            carry_one("bowl", "breakfast_table", "countertop"),
            {"breakfast_table": "dining_room_0", "countertop": "kitchen_0"}),
        sub("put the magazine from the sofa on the console table",
            carry_one("magazine", "sofa", "console_table"),
            {"sofa": "living_room_0", "console_table": "corridor_0"}),
        sub("put the tupperware from the kitchen countertop in the corridor bookcase",
            stow_one("tupperware", "countertop", "bookcase"),
            {"countertop": "kitchen_0", "bookcase": "corridor_0"}),
        sub("take the textbook out of the living room bookcase and put it on the breakfast table",
            retrieve_one("textbook", "bookcase", "breakfast_table"),
            {"bookcase": "living_room_0", "breakfast_table": "dining_room_0"},
            [inside("textbook", "bookcase")]),
        sub("switch on the floor lamp", switch_one("floor_lamp"),
            {"floor_lamp": "living_room_0"}),
        sub("put the tablespoon from the kitchen countertop away in the top cabinet",
            stow_closed("tablespoon", "countertop", "top_cabinet"),
            {"countertop": "kitchen_0", "top_cabinet": "kitchen_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("take the casserole from the kitchen countertop, heat it in the oven, and put it on the breakfast table",
            heat_and_serve("casserole", "countertop", "oven", "breakfast_table"),
            {"countertop": "kitchen_0", "oven": "kitchen_0", "breakfast_table": "dining_room_0"}),
        sub("take the casserole out of the fridge, warm it in the microwave, and leave it on the breakfast table",
            fetch_heat_serve("casserole", "fridge", "microwave", "breakfast_table"),
            {"fridge": "kitchen_0", "microwave": "kitchen_0", "breakfast_table": "dining_room_0"}),
        sub("put the bowl from the kitchen countertop in the dishwasher and run it",
            confer_in_place("bowl", "countertop", "dishwasher"),
            {"countertop": "kitchen_0", "dishwasher": "kitchen_0"}),
    ],
    "Rs_int": [
        sub("put the wineglass from the countertop on the breakfast table",
            carry_one("wineglass", "countertop", "breakfast_table"),
            {"countertop": "living_room_0", "breakfast_table": "living_room_0"}),
        sub("put the newspaper from the sofa in the bookcase",
            stow_one("newspaper", "sofa", "bookcase"),
            {"sofa": "living_room_0", "bookcase": "living_room_0"}),
        sub("put the rag from the countertop in the furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "living_room_0", "furniture_sink": "kitchen_0"}),
        sub("take the sponge out of the pedestal sink and put it on the coffee table",
            retrieve_one("sponge", "pedestal_sink", "coffee_table"),
            {"pedestal_sink": "bathroom_0", "coffee_table": "living_room_0"},
            [inside("sponge", "pedestal_sink")]),
        sub("put the plate from the breakfast table on the coffee table",
            carry_one("plate", "breakfast_table", "coffee_table"),
            {"breakfast_table": "living_room_0", "coffee_table": "living_room_0"}),
        sub("put the carton from the coffee table in the kitchen trash can",
            stow_one("carton", "coffee_table", "public_trash_can"),
            {"coffee_table": "living_room_0", "public_trash_can": "kitchen_0"}),
        sub("put the notebook from the bed on the countertop",
            carry_one("notebook", "bed", "countertop"),
            {"bed": "bedroom_0", "countertop": "living_room_0"}),
        sub("put the hand towel from the bed in the pedestal sink",
            stow_one("hand_towel", "bed", "pedestal_sink"),
            {"bed": "bedroom_0", "pedestal_sink": "bathroom_0"}),
        sub("take the bowl out of the furniture sink and put it on the breakfast table",
            retrieve_one("bowl", "furniture_sink", "breakfast_table"),
            {"furniture_sink": "kitchen_0", "breakfast_table": "living_room_0"},
            [inside("bowl", "furniture_sink")]),
        sub("put the magazine from the sofa on the bed",
            carry_one("magazine", "sofa", "bed"),
            {"sofa": "living_room_0", "bed": "bedroom_0"}),
        sub("switch on the floor lamp", switch_one("floor_lamp"),
            {"floor_lamp": "living_room_0"}),
        sub("put the tablespoon from the countertop away in the bedroom bottom cabinet",
            stow_closed("tablespoon", "countertop", "bottom_cabinet"),
            {"countertop": "living_room_0", "bottom_cabinet": "bedroom_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("take the sliced roast beef from the countertop, heat it in the oven, and put it on the breakfast table",
            heat_and_serve("sliced_roast_beef", "countertop", "oven", "breakfast_table"),
            {"countertop": "living_room_0", "oven": "kitchen_0", "breakfast_table": "living_room_0"}),
        sub("take the club sandwich out of the fridge, warm it in the microwave, and leave it on the countertop",
            fetch_heat_serve("club_sandwich", "fridge", "microwave", "countertop"),
            {"fridge": "kitchen_0", "microwave": "kitchen_0", "countertop": "living_room_0"}),
        sub("put the bowl from the countertop in the dishwasher and run it",
            confer_in_place("bowl", "countertop", "dishwasher"),
            {"countertop": "living_room_0", "dishwasher": "kitchen_0"}),
    ],
    "Beechwood_1_int": [
        sub("put the board game from the bedroom bed on the armchair",
            carry_one("board_game", "bed", "armchair"),
            {"bed": "bedroom_0", "armchair": "playroom_0"}),
        sub("put the jigsaw puzzle from the playroom breakfast table in the playroom bookcase",
            stow_one("jigsaw_puzzle", "breakfast_table", "bookcase"),
            {"breakfast_table": "playroom_0", "bookcase": "playroom_0"}),
        sub("put the rag from the bathroom countertop in the furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "bathroom_0", "furniture_sink": "bathroom_1"}),
        sub("take the teddy bear out of the child's room bookcase and put it on the sofa",
            retrieve_one("teddy_bear", "bookcase", "sofa"),
            {"bookcase": "childs_room_0", "sofa": "television_room_0"},
            [inside("teddy_bear", "bookcase")]),
        sub("put the pencil case from the child's room breakfast table on the bedroom bed",
            carry_one("pencil_case", "breakfast_table", "bed"),
            {"breakfast_table": "childs_room_1", "bed": "bedroom_0"}),
        sub("put the hand towel from the bathroom countertop in the furniture sink",
            stow_one("hand_towel", "countertop", "furniture_sink"),
            {"countertop": "bathroom_0", "furniture_sink": "bathroom_1"}),
        sub("put the newspaper from the sofa on the armchair",
            carry_one("newspaper", "sofa", "armchair"),
            {"sofa": "television_room_0", "armchair": "playroom_0"}),
        sub("put the colored pencil from the child's room bed in the child's room bookcase",
            stow_one("colored_pencil", "bed", "bookcase"),
            {"bed": "childs_room_1", "bookcase": "childs_room_0"}),
        sub("take the dice out of the playroom bookcase and put it on the child's room breakfast table",
            retrieve_one("dice", "bookcase", "breakfast_table"),
            {"bookcase": "playroom_0", "breakfast_table": "childs_room_1"},
            [inside("dice", "bookcase")]),
        sub("put the sponge from the bathroom countertop on the bedroom bed",
            carry_one("sponge", "countertop", "bed"),
            {"countertop": "bathroom_0", "bed": "bedroom_0"}),
        sub("switch on the table lamp", switch_one("table_lamp"),
            {"table_lamp": "playroom_0"}),
        sub("put the toothbrush from the bathroom countertop away in the bathroom top cabinet",
            stow_closed("toothbrush", "countertop", "top_cabinet"),
            {"countertop": "bathroom_0", "top_cabinet": "bathroom_0"}),
    ],
    "Ihlen_1_int": [
        sub("put the wineglass from the dining room countertop on the dining room breakfast table",
            carry_one("wineglass", "countertop", "breakfast_table"),
            {"countertop": "dining_room_0", "breakfast_table": "dining_room_0"}),
        sub("put the newspaper from the sofa in the bookcase",
            stow_one("newspaper", "sofa", "bookcase"),
            {"sofa": "living_room_0", "bookcase": "kitchen_0"}),
        sub("put the rag from the kitchen countertop in the furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "kitchen_0", "furniture_sink": "kitchen_0"}),
        sub("take the textbook out of the bookcase and put it on the coffee table",
            retrieve_one("textbook", "bookcase", "coffee_table"),
            {"bookcase": "kitchen_0", "coffee_table": "living_room_0"},
            [inside("textbook", "bookcase")]),
        sub("put the plate from the dining room breakfast table on the armchair",
            carry_one("plate", "breakfast_table", "armchair"),
            {"breakfast_table": "dining_room_0", "armchair": "living_room_0"}),
        sub("put the hand towel from the bedroom bed in the pedestal sink",
            stow_one("hand_towel", "bed", "pedestal_sink"),
            {"bed": "bedroom_0", "pedestal_sink": "bathroom_0"}),
        sub("put the notebook from the coffee table on the bedroom breakfast table",
            carry_one("notebook", "coffee_table", "breakfast_table"),
            {"coffee_table": "living_room_0", "breakfast_table": "bedroom_1"}),
        sub("put the sponge from the kitchen countertop in the bathtub",
            stow_one("sponge", "countertop", "bathtub"),
            {"countertop": "kitchen_0", "bathtub": "bathroom_0"}),
        sub("put the bowl from the kitchen countertop on the sofa",
            carry_one("bowl", "countertop", "sofa"),
            {"countertop": "kitchen_0", "sofa": "living_room_0"}),
        sub("put the magazine from the armchair on the bedroom bed",
            carry_one("magazine", "armchair", "bed"),
            {"armchair": "living_room_0", "bed": "bedroom_0"}),
        sub("switch on the bedroom table lamp", switch_one("table_lamp"),
            {"table_lamp": "bedroom_0"}),
        sub("put the hanger from the bedroom bed away in the bedroom bottom cabinet",
            stow_closed("hanger", "bed", "bottom_cabinet"),
            {"bed": "bedroom_0", "bottom_cabinet": "bedroom_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("take the pizza from the kitchen countertop, heat it in the oven, and put it on the bedroom breakfast table",
            heat_and_serve("pizza", "countertop", "oven", "breakfast_table"),
            {"countertop": "kitchen_0", "oven": "kitchen_0", "breakfast_table": "bedroom_1"}),
        sub("take the casserole out of the fridge, warm it in the oven, and leave it on the bedroom breakfast table",
            fetch_heat_serve("casserole", "fridge", "oven", "breakfast_table"),
            {"fridge": "kitchen_0", "oven": "kitchen_0", "breakfast_table": "bedroom_1"}),
        sub("put the water glass from the kitchen countertop in the dishwasher and run it",
            confer_in_place("water_glass", "countertop", "dishwasher"),
            {"countertop": "kitchen_0", "dishwasher": "kitchen_0"}),
    ],
    "Merom_1_int": [
        sub("put the wineglass from the breakfast table on the living room armchair",
            carry_one("wineglass", "breakfast_table", "armchair"),
            {"breakfast_table": "dining_room_0", "armchair": "living_room_0"}),
        sub("put the newspaper from the sofa in the bookcase",
            stow_one("newspaper", "sofa", "bookcase"),
            {"sofa": "living_room_0", "bookcase": "kitchen_0"}),
        sub("put the rag from the coffee table in the kitchen furniture sink",
            stow_one("rag", "coffee_table", "furniture_sink"),
            {"coffee_table": "living_room_0", "furniture_sink": "kitchen_0"}),
        sub("take the textbook out of the bookcase and put it on the breakfast table",
            retrieve_one("textbook", "bookcase", "breakfast_table"),
            {"bookcase": "kitchen_0", "breakfast_table": "dining_room_0"},
            [inside("textbook", "bookcase")]),
        sub("put the board game from the child's room bed on the coffee table",
            carry_one("board_game", "bed", "coffee_table"),
            {"bed": "childs_room_0", "coffee_table": "living_room_0"}),
        sub("put the hand towel from the bedroom bed in the bathroom furniture sink",
            stow_one("hand_towel", "bed", "furniture_sink"),
            {"bed": "bedroom_0", "furniture_sink": "bathroom_0"}),
        sub("put the carton from the coffee table in the kitchen trash can",
            stow_one("carton", "coffee_table", "public_trash_can"),
            {"coffee_table": "living_room_0", "public_trash_can": "kitchen_0"}),
        sub("put the t-shirt from the bedroom bed in the hamper",
            stow_one("t_shirt", "bed", "hamper"),
            {"bed": "bedroom_0", "hamper": "bedroom_0"}),
        sub("put the plate from the breakfast table on the sofa",
            carry_one("plate", "breakfast_table", "sofa"),
            {"breakfast_table": "dining_room_0", "sofa": "living_room_0"}),
        sub("put the teddy bear from the child's room armchair on the child's room bed",
            carry_one("teddy_bear", "armchair", "bed"),
            {"armchair": "childs_room_0", "bed": "childs_room_0"}),
        sub("switch on the bedroom table lamp", switch_one("table_lamp"),
            {"table_lamp": "bedroom_0"}),
        sub("put the hanger from the bedroom bed away in the bedroom bottom cabinet",
            stow_closed("hanger", "bed", "bottom_cabinet"),
            {"bed": "bedroom_0", "bottom_cabinet": "bedroom_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("put the saucepan from the stove in the dishwasher and run it",
            confer_in_place("saucepan", "stove", "dishwasher"),
            {"stove": "kitchen_0", "dishwasher": "kitchen_0"}),
    ],
    "Pomaria_0_int": [
        sub("put the newspaper from the sofa in the living room bookcase",
            stow_one("newspaper", "sofa", "bookcase"),
            {"sofa": "living_room_0", "bookcase": "living_room_0"}),
        sub("put the magazine from the office countertop in the office bookcase",
            stow_one("magazine", "countertop", "bookcase"),
            {"countertop": "private_office_0", "bookcase": "private_office_0"}),
        sub("put the rag from the bedroom bed in the furniture sink",
            stow_one("rag", "bed", "furniture_sink"),
            {"bed": "bedroom_0", "furniture_sink": "bathroom_0"}),
        sub("take the textbook out of the corridor bookcase and put it on the coffee table",
            retrieve_one("textbook", "bookcase", "coffee_table"),
            {"bookcase": "corridor_0", "coffee_table": "living_room_0"},
            [inside("textbook", "bookcase")]),
        sub("put the keyboard from the office breakfast table on the office countertop",
            carry_one("keyboard", "breakfast_table", "countertop"),
            {"breakfast_table": "private_office_0", "countertop": "private_office_0"}),
        sub("put the hand towel from the bedroom bed in the bathtub",
            stow_one("hand_towel", "bed", "bathtub"),
            {"bed": "bedroom_0", "bathtub": "bathroom_0"}),
        sub("put the notebook from the armchair on the bedroom breakfast table",
            carry_one("notebook", "armchair", "breakfast_table"),
            {"armchair": "living_room_0", "breakfast_table": "bedroom_1"}),
        sub("put the mail from the office countertop in the bedroom bookcase",
            stow_one("mail", "countertop", "bookcase"),
            {"countertop": "private_office_0", "bookcase": "bedroom_0"}),
        sub("put the pot plant from the coffee table on the sofa",
            carry_one("pot_plant", "coffee_table", "sofa"),
            {"coffee_table": "living_room_0", "sofa": "living_room_0"}),
        sub("put the dress from the bedroom bed in the bedroom bookcase",
            stow_one("dress", "bed", "bookcase"),
            {"bed": "bedroom_1", "bookcase": "bedroom_0"}),
        sub("put the legal document from the office countertop away in the office bottom cabinet",
            stow_closed("legal_document", "countertop", "bottom_cabinet"),
            {"countertop": "private_office_0", "bottom_cabinet": "private_office_0"}),
    ],
    "Pomaria_1_int": [
        sub("put the wineglass from the kitchen countertop on the breakfast table",
            carry_one("wineglass", "countertop", "breakfast_table"),
            {"countertop": "kitchen_0", "breakfast_table": "kitchen_0"}),
        sub("put the newspaper from the armchair in the living room bookcase",
            stow_one("newspaper", "armchair", "bookcase"),
            {"armchair": "living_room_0", "bookcase": "living_room_0"}),
        sub("put the rag from the kitchen countertop in the bathroom furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "kitchen_0", "furniture_sink": "bathroom_0"}),
        sub("take the textbook out of the corridor bookcase and put it on the living room coffee table",
            retrieve_one("textbook", "bookcase", "coffee_table"),
            {"bookcase": "corridor_0", "coffee_table": "living_room_0"},
            [inside("textbook", "bookcase")]),
        sub("put the plate from the pantry countertop on the breakfast table",
            carry_one("plate", "countertop", "breakfast_table"),
            {"countertop": "pantry_room_0", "breakfast_table": "kitchen_0"}),
        sub("put the detergent bottle from the kitchen countertop in the pedestal sink",
            stow_one("detergent_bottle", "countertop", "pedestal_sink"),
            {"countertop": "kitchen_0", "pedestal_sink": "utility_room_0"}),
        sub("put the notebook from the living room coffee table on the armchair",
            carry_one("notebook", "coffee_table", "armchair"),
            {"coffee_table": "living_room_0", "armchair": "living_room_0"}),
        sub("put the bowl from the breakfast table in the kitchen furniture sink",
            stow_one("bowl", "breakfast_table", "furniture_sink"),
            {"breakfast_table": "kitchen_0", "furniture_sink": "kitchen_0"}),
        sub("put the magazine from the armchair on the corridor coffee table",
            carry_one("magazine", "armchair", "coffee_table"),
            {"armchair": "living_room_0", "coffee_table": "corridor_0"}),
        sub("put the hand towel from the pantry countertop in the bathroom furniture sink",
            stow_one("hand_towel", "countertop", "furniture_sink"),
            {"countertop": "pantry_room_0", "furniture_sink": "bathroom_0"}),
        sub("put the tablespoon from the kitchen countertop away in the kitchen bottom cabinet",
            stow_closed("tablespoon", "countertop", "bottom_cabinet"),
            {"countertop": "kitchen_0", "bottom_cabinet": "kitchen_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("take the cinnamon roll from the kitchen countertop, heat it in the oven, and put it on the breakfast table",
            heat_and_serve("cinnamon_roll", "countertop", "oven", "breakfast_table"),
            {"countertop": "kitchen_0", "oven": "kitchen_0", "breakfast_table": "kitchen_0"}),
        sub("take the casserole out of the kitchen fridge, warm it in the microwave, and leave it on the breakfast table",
            fetch_heat_serve("casserole", "fridge", "microwave", "breakfast_table"),
            {"fridge": "kitchen_0", "microwave": "kitchen_0", "breakfast_table": "kitchen_0"}),
        sub("put the bath towel from the utility room bottom cabinet in the clothes dryer and run it",
            confer_in_place("bath_towel", "bottom_cabinet", "clothes_dryer"),
            {"bottom_cabinet": "utility_room_0", "clothes_dryer": "utility_room_0"}),
        sub("put the frying pan from the burner in the dishwasher and run it",
            confer_in_place("frying_pan", "burner", "dishwasher"),
            {"burner": "kitchen_0", "dishwasher": "kitchen_0"}),
    ],
    "Wainscott_0_int": [
        # This scene is in two pieces and the survey's `reachable` names the one the
        # benchmark does not use. These rooms are the piece the single-task tasks work in.
        sub("put the wineglass from the countertop on the breakfast table",
            carry_one("wineglass", "countertop", "breakfast_table"),
            {"countertop": "kitchen_0", "breakfast_table": "dining_room_0"}),
        sub("put the newspaper from the sofa on the living room coffee table",
            carry_one("newspaper", "sofa", "coffee_table"),
            {"sofa": "living_room_1", "coffee_table": "living_room_1"}),
        sub("put the rag from the countertop in the furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "kitchen_0", "furniture_sink": "kitchen_0"}),
        sub("take the textbook out of the bookcase and put it on the armchair",
            retrieve_one("textbook", "bookcase", "armchair"),
            {"bookcase": "kitchen_0", "armchair": "living_room_1"},
            [inside("textbook", "bookcase")]),
        sub("put the plate from the countertop on the console table",
            carry_one("plate", "countertop", "console_table"),
            {"countertop": "kitchen_0", "console_table": "living_room_1"}),
        sub("put the bowl from the breakfast table in the furniture sink",
            stow_one("bowl", "breakfast_table", "furniture_sink"),
            {"breakfast_table": "dining_room_0", "furniture_sink": "kitchen_0"}),
        sub("put the notebook from the living room coffee table in the bookcase",
            stow_one("notebook", "coffee_table", "bookcase"),
            {"coffee_table": "living_room_1", "bookcase": "kitchen_0"}),
        sub("put the magazine from the sofa on the living room breakfast table",
            carry_one("magazine", "sofa", "breakfast_table"),
            {"sofa": "living_room_1", "breakfast_table": "living_room_1"}),
        sub("put the tupperware from the countertop on the kitchen coffee table",
            carry_one("tupperware", "countertop", "coffee_table"),
            {"countertop": "kitchen_0", "coffee_table": "kitchen_0"}),
        sub("put the carving knife from the dining room breakfast table in the furniture sink",
            stow_one("carving_knife", "breakfast_table", "furniture_sink"),
            {"breakfast_table": "dining_room_0", "furniture_sink": "kitchen_0"}),
        sub("switch on the floor lamp", switch_one("floor_lamp"),
            {"floor_lamp": "living_room_1"}),
        sub("put the tablespoon from the dining room breakfast table away in the dining room bottom cabinet",
            stow_closed("tablespoon", "breakfast_table", "bottom_cabinet"),
            {"breakfast_table": "dining_room_0", "bottom_cabinet": "dining_room_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("take the casserole from the countertop, heat it in the oven, and put it on the living room breakfast table",
            heat_and_serve("casserole", "countertop", "oven", "breakfast_table"),
            {"countertop": "kitchen_0", "oven": "kitchen_0", "breakfast_table": "living_room_1"}),
        sub("take the swiss cheese out of the fridge, warm it in the microwave, and leave it on the living room breakfast table",
            fetch_heat_serve("swiss_cheese", "fridge", "microwave", "breakfast_table"),
            {"fridge": "kitchen_0", "microwave": "kitchen_0", "breakfast_table": "living_room_1"}),
        sub("put the crock pot from the stove in the dishwasher and run it",
            confer_in_place("crock_pot", "stove", "dishwasher"),
            {"stove": "kitchen_0", "dishwasher": "kitchen_0"}),
    ],
    "Wainscott_1_int": [
        sub("put the newspaper from the armchair on the playroom coffee table",
            carry_one("newspaper", "armchair", "coffee_table"),
            {"armchair": "bedroom_0", "coffee_table": "playroom_0"}),
        sub("put the rag from the countertop in the furniture sink",
            stow_one("rag", "countertop", "furniture_sink"),
            {"countertop": "bathroom_0", "furniture_sink": "bathroom_1"}),
        sub("take the sponge out of the utility room pedestal sink and put it on the armchair",
            retrieve_one("sponge", "pedestal_sink", "armchair"),
            {"pedestal_sink": "utility_room_0", "armchair": "bedroom_0"},
            [inside("sponge", "pedestal_sink")]),
        sub("put the hand towel from the bedroom bed in the bathtub",
            stow_one("hand_towel", "bed", "bathtub"),
            {"bed": "bedroom_0", "bathtub": "bathroom_0"}),
        sub("put the notebook from the bedroom breakfast table on the pool table",
            carry_one("notebook", "breakfast_table", "pool_table"),
            {"breakfast_table": "bedroom_0", "pool_table": "playroom_0"}),
        sub("put the magazine from the playroom coffee table on the armchair",
            carry_one("magazine", "coffee_table", "armchair"),
            {"coffee_table": "playroom_0", "armchair": "bedroom_0"}),
        sub("put the t-shirt from the bedroom bed on the bedroom breakfast table",
            carry_one("t_shirt", "bed", "breakfast_table"),
            {"bed": "bedroom_1", "breakfast_table": "bedroom_0"}),
        sub("put the carton from the countertop in the bathroom trash can",
            stow_one("carton", "countertop", "public_trash_can"),
            {"countertop": "bathroom_0", "public_trash_can": "bathroom_1"}),
        sub("put the detergent bottle from the countertop in the utility room pedestal sink",
            stow_one("detergent_bottle", "countertop", "pedestal_sink"),
            {"countertop": "bathroom_0", "pedestal_sink": "utility_room_0"}),
        sub("put the dress from the bedroom bed on the playroom breakfast table",
            carry_one("dress", "bed", "breakfast_table"),
            {"bed": "bedroom_2", "breakfast_table": "playroom_0"}),
        sub("switch on the bedroom table lamp", switch_one("table_lamp"),
            {"table_lamp": "bedroom_0"}),
        sub("put the toothbrush from the countertop away in the bathroom bottom cabinet",
            stow_closed("toothbrush", "countertop", "bottom_cabinet"),
            {"countertop": "bathroom_0", "bottom_cabinet": "bathroom_0"}),
        # --- conferred-state errands: the same shapes and the same arguments
        # --- the single-task benchmark already verifies, plus the short
        # --- `confer_in_place` form where the long one only added carrying ---
        sub("put the t shirt from the bedroom bottom cabinet in the clothes dryer and run it",
            confer_in_place("t_shirt", "bottom_cabinet", "clothes_dryer"),
            {"bottom_cabinet": "bedroom_0", "clothes_dryer": "utility_room_0"}),
        sub("put the bath towel from the playroom top cabinet in the clothes dryer and run it",
            confer_in_place("bath_towel", "top_cabinet", "clothes_dryer"),
            {"top_cabinet": "playroom_0", "clothes_dryer": "utility_room_0"}),
    ],
}
